stages:
  - test
coverage:
  stage: test
  script:
    - docker-compose build
    - docker-compose run --rm mcserver bash -c "source ../venv/bin/activate && coverage run --rcfile=.coveragerc tests.py && coverage combine && coverage report -m"
  coverage: '/^TOTAL.+?(\d+\%)$/'
  tags:
    - python
    - pip
    - flask
