version: '3.7'

services:
  csm:
    build:
      context: .
      dockerfile: Dockerfile
    command: /home/mc/venv/bin/gunicorn -c csm/gunicorn_config.py run_csm:app
    depends_on:
      - db
    environment:
      - FLASK_APP=run_csm.py
      - IS_THIS_A_DOCKER_CONTAINER=Yes
      - PYTHONPATH=/home/mc
    ports:
      - "8122:22"
      - "6555:6555"
    restart: always
    stdin_open: true
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
  mcserver:
    build:
      context: .
      dockerfile: Dockerfile
    command: /home/mc/venv/bin/gunicorn -c mcserver/gunicorn_config.py app:app
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - IS_THIS_A_DOCKER_CONTAINER=Yes
      - PYTHONPATH=/home/mc
    networks:
      - mc_backend
    ports:
      - "8022:22"
      - "5000:5000"
    restart: always
    stdin_open: true
networks:
  mc_backend:
    external:
      name: mc_backend_default
volumes:
  db-data:
