stages:
  - build
  - ci
  - coverage
build:
  stage: build
  script:
    - docker-compose build
ci_frontend:
  stage: ci
  script:
    - ./ci_frontend.sh
  artifacts:
    paths:
      - ci_frontend.log
ci_backend:
  stage: ci
  script:
    - ./ci_backend.sh
  artifacts:
    paths:
      - ci_backend.log
coverage:
  stage: coverage
  script:
    - ./coverage.sh
    - cat coverage.log
  artifacts:
    paths:
      - coverage.log
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
