stages:
  - build
  - ci
  - coverage
build:
  stage: build
  script:
    - docker-compose build
ci_frontend:
  stage: ci
  script:
    - docker-compose run --rm --entrypoint="npm run test-ci" mc_frontend > ci_frontend.log
  artifacts:
    paths:
      - ci_frontend.log
ci_backend:
  stage: ci
  script:
    - docker-compose run --rm mcserver bash -c "source ../venv/bin/activate && coverage run --rcfile=.coveragerc tests.py && coverage combine && coverage report -m" > ci_backend.log
  artifacts:
    paths:
      - ci_backend.log
coverage:
  stage: coverage
  script:
    - ./coverage_ci.sh
    - cat coverage.log
  artifacts:
    paths:
      - coverage.log
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
