# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi.openapi_server.models.base_model_ import Model
from openapi.openapi_server import util


class AnnisResponseFrequencyAnalysis(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, count=None, phenomena=None, values=None):  # noqa: E501
        """AnnisResponseFrequencyAnalysis - a model defined in OpenAPI

        :param count: The count of this AnnisResponseFrequencyAnalysis.  # noqa: E501
        :type count: int
        :param phenomena: The phenomena of this AnnisResponseFrequencyAnalysis.  # noqa: E501
        :type phenomena: List[str]
        :param values: The values of this AnnisResponseFrequencyAnalysis.  # noqa: E501
        :type values: List[str]
        """
        self.openapi_types = {
            'count': int,
            'phenomena': List[str],
            'values': List[str]
        }

        self.attribute_map = {
            'count': 'count',
            'phenomena': 'phenomena',
            'values': 'values'
        }

        self._count = count
        self._phenomena = phenomena
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'AnnisResponseFrequencyAnalysis':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnnisResponse_frequency_analysis of this AnnisResponseFrequencyAnalysis.  # noqa: E501
        :rtype: AnnisResponseFrequencyAnalysis
        """
        return util.deserialize_model(dikt, cls)

    @property
    def count(self):
        """Gets the count of this AnnisResponseFrequencyAnalysis.

        How often the given combination of values occurred.  # noqa: E501

        :return: The count of this AnnisResponseFrequencyAnalysis.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this AnnisResponseFrequencyAnalysis.

        How often the given combination of values occurred.  # noqa: E501

        :param count: The count of this AnnisResponseFrequencyAnalysis.
        :type count: int
        """

        self._count = count

    @property
    def phenomena(self):
        """Gets the phenomena of this AnnisResponseFrequencyAnalysis.

        Labels for the phenomena described in this frequency entry.  # noqa: E501

        :return: The phenomena of this AnnisResponseFrequencyAnalysis.
        :rtype: List[str]
        """
        return self._phenomena

    @phenomena.setter
    def phenomena(self, phenomena):
        """Sets the phenomena of this AnnisResponseFrequencyAnalysis.

        Labels for the phenomena described in this frequency entry.  # noqa: E501

        :param phenomena: The phenomena of this AnnisResponseFrequencyAnalysis.
        :type phenomena: List[str]
        """

        self._phenomena = phenomena

    @property
    def values(self):
        """Gets the values of this AnnisResponseFrequencyAnalysis.

        Values for the phenomena described in this frequency entry.  # noqa: E501

        :return: The values of this AnnisResponseFrequencyAnalysis.
        :rtype: List[str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this AnnisResponseFrequencyAnalysis.

        Values for the phenomena described in this frequency entry.  # noqa: E501

        :param values: The values of this AnnisResponseFrequencyAnalysis.
        :type values: List[str]
        """

        self._values = values
