# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi.openapi_server.models.base_model_ import Model
from openapi.openapi_server.models.exercise_base import ExerciseBase
from openapi.openapi_server.models.exercise_form_all_of import ExerciseFormAllOf
from openapi.openapi_server import util

from openapi.openapi_server.models.exercise_base import ExerciseBase  # noqa: E501
from openapi.openapi_server.models.exercise_form_all_of import ExerciseFormAllOf  # noqa: E501

class ExerciseForm(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, correct_feedback='', general_feedback='', incorrect_feedback='', instructions='', language='de', partially_correct_feedback='', search_values='[]', work_author='', work_title='', type=None, type_translation='', urn=None):  # noqa: E501
        """ExerciseForm - a model defined in OpenAPI

        :param correct_feedback: The correct_feedback of this ExerciseForm.  # noqa: E501
        :type correct_feedback: str
        :param general_feedback: The general_feedback of this ExerciseForm.  # noqa: E501
        :type general_feedback: str
        :param incorrect_feedback: The incorrect_feedback of this ExerciseForm.  # noqa: E501
        :type incorrect_feedback: str
        :param instructions: The instructions of this ExerciseForm.  # noqa: E501
        :type instructions: str
        :param language: The language of this ExerciseForm.  # noqa: E501
        :type language: str
        :param partially_correct_feedback: The partially_correct_feedback of this ExerciseForm.  # noqa: E501
        :type partially_correct_feedback: str
        :param search_values: The search_values of this ExerciseForm.  # noqa: E501
        :type search_values: str
        :param work_author: The work_author of this ExerciseForm.  # noqa: E501
        :type work_author: str
        :param work_title: The work_title of this ExerciseForm.  # noqa: E501
        :type work_title: str
        :param type: The type of this ExerciseForm.  # noqa: E501
        :type type: str
        :param type_translation: The type_translation of this ExerciseForm.  # noqa: E501
        :type type_translation: str
        :param urn: The urn of this ExerciseForm.  # noqa: E501
        :type urn: str
        """
        self.openapi_types = {
            'correct_feedback': str,
            'general_feedback': str,
            'incorrect_feedback': str,
            'instructions': str,
            'language': str,
            'partially_correct_feedback': str,
            'search_values': str,
            'work_author': str,
            'work_title': str,
            'type': str,
            'type_translation': str,
            'urn': str
        }

        self.attribute_map = {
            'correct_feedback': 'correct_feedback',
            'general_feedback': 'general_feedback',
            'incorrect_feedback': 'incorrect_feedback',
            'instructions': 'instructions',
            'language': 'language',
            'partially_correct_feedback': 'partially_correct_feedback',
            'search_values': 'search_values',
            'work_author': 'work_author',
            'work_title': 'work_title',
            'type': 'type',
            'type_translation': 'type_translation',
            'urn': 'urn'
        }

        self._correct_feedback = correct_feedback
        self._general_feedback = general_feedback
        self._incorrect_feedback = incorrect_feedback
        self._instructions = instructions
        self._language = language
        self._partially_correct_feedback = partially_correct_feedback
        self._search_values = search_values
        self._work_author = work_author
        self._work_title = work_title
        self._type = type
        self._type_translation = type_translation
        self._urn = urn

    @classmethod
    def from_dict(cls, dikt) -> 'ExerciseForm':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExerciseForm of this ExerciseForm.  # noqa: E501
        :rtype: ExerciseForm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def correct_feedback(self):
        """Gets the correct_feedback of this ExerciseForm.

        Feedback for successful completion of the exercise.  # noqa: E501

        :return: The correct_feedback of this ExerciseForm.
        :rtype: str
        """
        return self._correct_feedback

    @correct_feedback.setter
    def correct_feedback(self, correct_feedback):
        """Sets the correct_feedback of this ExerciseForm.

        Feedback for successful completion of the exercise.  # noqa: E501

        :param correct_feedback: The correct_feedback of this ExerciseForm.
        :type correct_feedback: str
        """

        self._correct_feedback = correct_feedback

    @property
    def general_feedback(self):
        """Gets the general_feedback of this ExerciseForm.

        Feedback for finishing the exercise.  # noqa: E501

        :return: The general_feedback of this ExerciseForm.
        :rtype: str
        """
        return self._general_feedback

    @general_feedback.setter
    def general_feedback(self, general_feedback):
        """Sets the general_feedback of this ExerciseForm.

        Feedback for finishing the exercise.  # noqa: E501

        :param general_feedback: The general_feedback of this ExerciseForm.
        :type general_feedback: str
        """

        self._general_feedback = general_feedback

    @property
    def incorrect_feedback(self):
        """Gets the incorrect_feedback of this ExerciseForm.

        Feedback for failing to complete the exercise successfully.  # noqa: E501

        :return: The incorrect_feedback of this ExerciseForm.
        :rtype: str
        """
        return self._incorrect_feedback

    @incorrect_feedback.setter
    def incorrect_feedback(self, incorrect_feedback):
        """Sets the incorrect_feedback of this ExerciseForm.

        Feedback for failing to complete the exercise successfully.  # noqa: E501

        :param incorrect_feedback: The incorrect_feedback of this ExerciseForm.
        :type incorrect_feedback: str
        """

        self._incorrect_feedback = incorrect_feedback

    @property
    def instructions(self):
        """Gets the instructions of this ExerciseForm.

        Hints for how to complete the exercise.  # noqa: E501

        :return: The instructions of this ExerciseForm.
        :rtype: str
        """
        return self._instructions

    @instructions.setter
    def instructions(self, instructions):
        """Sets the instructions of this ExerciseForm.

        Hints for how to complete the exercise.  # noqa: E501

        :param instructions: The instructions of this ExerciseForm.
        :type instructions: str
        """
        if instructions is None:
            raise ValueError("Invalid value for `instructions`, must not be `None`")  # noqa: E501

        self._instructions = instructions

    @property
    def language(self):
        """Gets the language of this ExerciseForm.

        ISO 639-1 Language Code for the localization of exercise content.  # noqa: E501

        :return: The language of this ExerciseForm.
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this ExerciseForm.

        ISO 639-1 Language Code for the localization of exercise content.  # noqa: E501

        :param language: The language of this ExerciseForm.
        :type language: str
        """

        self._language = language

    @property
    def partially_correct_feedback(self):
        """Gets the partially_correct_feedback of this ExerciseForm.

        Feedback for successfully completing certain parts of the exercise.  # noqa: E501

        :return: The partially_correct_feedback of this ExerciseForm.
        :rtype: str
        """
        return self._partially_correct_feedback

    @partially_correct_feedback.setter
    def partially_correct_feedback(self, partially_correct_feedback):
        """Sets the partially_correct_feedback of this ExerciseForm.

        Feedback for successfully completing certain parts of the exercise.  # noqa: E501

        :param partially_correct_feedback: The partially_correct_feedback of this ExerciseForm.
        :type partially_correct_feedback: str
        """

        self._partially_correct_feedback = partially_correct_feedback

    @property
    def search_values(self):
        """Gets the search_values of this ExerciseForm.

        Search queries that were used to build the exercise.  # noqa: E501

        :return: The search_values of this ExerciseForm.
        :rtype: str
        """
        return self._search_values

    @search_values.setter
    def search_values(self, search_values):
        """Sets the search_values of this ExerciseForm.

        Search queries that were used to build the exercise.  # noqa: E501

        :param search_values: The search_values of this ExerciseForm.
        :type search_values: str
        """
        if search_values is None:
            raise ValueError("Invalid value for `search_values`, must not be `None`")  # noqa: E501

        self._search_values = search_values

    @property
    def work_author(self):
        """Gets the work_author of this ExerciseForm.

        Name of the person who wrote the base text for the exercise.  # noqa: E501

        :return: The work_author of this ExerciseForm.
        :rtype: str
        """
        return self._work_author

    @work_author.setter
    def work_author(self, work_author):
        """Sets the work_author of this ExerciseForm.

        Name of the person who wrote the base text for the exercise.  # noqa: E501

        :param work_author: The work_author of this ExerciseForm.
        :type work_author: str
        """

        self._work_author = work_author

    @property
    def work_title(self):
        """Gets the work_title of this ExerciseForm.

        Title of the base text for the exercise.  # noqa: E501

        :return: The work_title of this ExerciseForm.
        :rtype: str
        """
        return self._work_title

    @work_title.setter
    def work_title(self, work_title):
        """Sets the work_title of this ExerciseForm.

        Title of the base text for the exercise.  # noqa: E501

        :param work_title: The work_title of this ExerciseForm.
        :type work_title: str
        """

        self._work_title = work_title

    @property
    def type(self):
        """Gets the type of this ExerciseForm.

        Type of exercise, concerning interaction and layout.  # noqa: E501

        :return: The type of this ExerciseForm.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ExerciseForm.

        Type of exercise, concerning interaction and layout.  # noqa: E501

        :param type: The type of this ExerciseForm.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def type_translation(self):
        """Gets the type_translation of this ExerciseForm.

        Localized expression of the exercise type.  # noqa: E501

        :return: The type_translation of this ExerciseForm.
        :rtype: str
        """
        return self._type_translation

    @type_translation.setter
    def type_translation(self, type_translation):
        """Sets the type_translation of this ExerciseForm.

        Localized expression of the exercise type.  # noqa: E501

        :param type_translation: The type_translation of this ExerciseForm.
        :type type_translation: str
        """

        self._type_translation = type_translation

    @property
    def urn(self):
        """Gets the urn of this ExerciseForm.

        CTS URN for the text passage from which the exercise was created.  # noqa: E501

        :return: The urn of this ExerciseForm.
        :rtype: str
        """
        return self._urn

    @urn.setter
    def urn(self, urn):
        """Sets the urn of this ExerciseForm.

        CTS URN for the text passage from which the exercise was created.  # noqa: E501

        :param urn: The urn of this ExerciseForm.
        :type urn: str
        """
        if urn is None:
            raise ValueError("Invalid value for `urn`, must not be `None`")  # noqa: E501

        self._urn = urn
