# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi.openapi_server.models.base_model_ import Model
from openapi.openapi_server import util


class MatchingExerciseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, exercise_type_translation=None, matching_degree=None):  # noqa: E501
        """MatchingExerciseAllOf - a model defined in OpenAPI

        :param exercise_type_translation: The exercise_type_translation of this MatchingExerciseAllOf.  # noqa: E501
        :type exercise_type_translation: str
        :param matching_degree: The matching_degree of this MatchingExerciseAllOf.  # noqa: E501
        :type matching_degree: float
        """
        self.openapi_types = {
            'exercise_type_translation': str,
            'matching_degree': float
        }

        self.attribute_map = {
            'exercise_type_translation': 'exercise_type_translation',
            'matching_degree': 'matching_degree'
        }

        self._exercise_type_translation = exercise_type_translation
        self._matching_degree = matching_degree

    @classmethod
    def from_dict(cls, dikt) -> 'MatchingExerciseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MatchingExercise_allOf of this MatchingExerciseAllOf.  # noqa: E501
        :rtype: MatchingExerciseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def exercise_type_translation(self):
        """Gets the exercise_type_translation of this MatchingExerciseAllOf.

        Localized expression of the exercise type.  # noqa: E501

        :return: The exercise_type_translation of this MatchingExerciseAllOf.
        :rtype: str
        """
        return self._exercise_type_translation

    @exercise_type_translation.setter
    def exercise_type_translation(self, exercise_type_translation):
        """Sets the exercise_type_translation of this MatchingExerciseAllOf.

        Localized expression of the exercise type.  # noqa: E501

        :param exercise_type_translation: The exercise_type_translation of this MatchingExerciseAllOf.
        :type exercise_type_translation: str
        """

        self._exercise_type_translation = exercise_type_translation

    @property
    def matching_degree(self):
        """Gets the matching_degree of this MatchingExerciseAllOf.

        Percentage of words in the exercise that match a reference vocabulary.  # noqa: E501

        :return: The matching_degree of this MatchingExerciseAllOf.
        :rtype: float
        """
        return self._matching_degree

    @matching_degree.setter
    def matching_degree(self, matching_degree):
        """Sets the matching_degree of this MatchingExerciseAllOf.

        Percentage of words in the exercise that match a reference vocabulary.  # noqa: E501

        :param matching_degree: The matching_degree of this MatchingExerciseAllOf.
        :type matching_degree: float
        """

        self._matching_degree = matching_degree
