# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi.openapi_server.models.base_model_ import Model
from openapi.openapi_server import util


class VocabularyMC(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AGLDT = "agldt"
    BWS = "bws"
    PROIEL = "proiel"
    VIVA = "viva"
    def __init__(self):  # noqa: E501
        """VocabularyMC - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'VocabularyMC':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VocabularyMC of this VocabularyMC.  # noqa: E501
        :rtype: VocabularyMC
        """
        return util.deserialize_model(dikt, cls)
