"""empty message

Revision ID: 309cade7121b
Revises: b8763e7091c2
Create Date: 2019-07-16 13:12:10.888942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309cade7121b'
down_revision = 'b8763e7091c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Exercise', sa.Column('urn', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Exercise', 'urn')
    # ### end Alembic commands ###
