"""empty message

Revision ID: 7d882cd4ce1f
Revises: 
Create Date: 2018-07-13 10:42:16.608026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d882cd4ce1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Corpus', sa.Column('citation_level_1', sa.String(), server_default='default', nullable=False))
    op.add_column('Corpus', sa.Column('citation_level_2', sa.String(), server_default='default', nullable=False))
    op.add_column('Corpus', sa.Column('citation_level_3', sa.String(), server_default='default', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Corpus', 'citation_level_3')
    op.drop_column('Corpus', 'citation_level_2')
    op.drop_column('Corpus', 'citation_level_1')
    # ### end Alembic commands ###
