"""empty message

Revision ID: 8ba6be1af780
Revises: 7d882cd4ce1f
Create Date: 2018-10-11 11:17:19.556727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba6be1af780'
down_revision = '7d882cd4ce1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Exercise', sa.Column('correct_feedback', sa.String(), nullable=True))
    op.add_column('Exercise', sa.Column('exercise_type', sa.String(), nullable=False, server_default='ddwtos'))
    op.add_column('Exercise', sa.Column('exercise_type_translation', sa.String(), nullable=True))
    op.add_column('Exercise', sa.Column('general_feedback', sa.String(), nullable=True))
    op.add_column('Exercise', sa.Column('incorrect_feedback', sa.String(), nullable=True))
    op.add_column('Exercise', sa.Column('instructions', sa.String(), nullable=True))
    op.add_column('Exercise', sa.Column('partially_correct_feedback', sa.String(), nullable=True))
    op.add_column('Exercise', sa.Column('solutions', sa.String(), nullable=False, server_default='[]'))
    op.add_column('Exercise', sa.Column('text', sa.String(), nullable=False, server_default=''))
    op.drop_column('Exercise', 'xml')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Exercise', sa.Column('xml', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Exercise', 'text')
    op.drop_column('Exercise', 'solutions')
    op.drop_column('Exercise', 'partially_correct_feedback')
    op.drop_column('Exercise', 'instructions')
    op.drop_column('Exercise', 'incorrect_feedback')
    op.drop_column('Exercise', 'general_feedback')
    op.drop_column('Exercise', 'exercise_type_translation')
    op.drop_column('Exercise', 'exercise_type')
    op.drop_column('Exercise', 'correct_feedback')
    # ### end Alembic commands ###
