"""empty message

Revision ID: 905858a5c465
Revises: 382b09e85c8b
Create Date: 2019-10-17 13:37:33.390399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905858a5c465'
down_revision = '382b09e85c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Exercise', sa.Column('text_complexity', sa.Float(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Exercise', 'text_complexity')
    # ### end Alembic commands ###
