"""empty message

Revision ID: b8763e7091c2
Revises: c4e24d8aed64
Create Date: 2019-02-06 13:06:23.381591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8763e7091c2'
down_revision = 'c4e24d8aed64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Exercise', sa.Column('search_values', sa.String(), server_default='', nullable=True))
    op.add_column('Exercise', sa.Column('work_author', sa.String(), server_default='', nullable=True))
    op.add_column('Exercise', sa.Column('work_title', sa.String(), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Exercise', 'work_title')
    op.drop_column('Exercise', 'work_author')
    op.drop_column('Exercise', 'search_values')
    # ### end Alembic commands ###
