openapi: "3.0.0"

info:
  title: Machina Callida Backend REST API
  version: "1.0"
servers:
  - url: http://localhost:5000/mc/api/v1.0

paths:
  /corpora:
    get:
      summary: Returns a list of corpora.
      operationId: mcserver.app.api.corpusListAPI.get
      responses:
        200:
          description: Corpus list
          content:
            application/json:
              schema:
                $ref: '../openapi_models.yaml#/components/schemas/Corpus'
      parameters:
        - name: last_update_time
          in: query
          description: Time (in milliseconds) of the last update.
          required: true
          schema:
            type: integer
            example: 123456789
  /corpora/{cid}:
    parameters:
      - name: cid
        in: path
        description: Corpus identifier.
        required: true
        schema:
          type: integer
          example: 1
    delete:
      summary: Deletes a single corpus by ID.
      operationId: mcserver.app.api.corpusAPI.delete
      responses:
        200:
          description: Indication of success
          content:
            application/json:
              schema:
                type: boolean
                example: true
    get:
      summary: Returns a single corpus by ID.
      operationId: mcserver.app.api.corpusAPI.get
      responses:
        200:
          description: Corpus object
          content:
            application/json:
              schema:
                $ref: '../openapi_models.yaml#/components/schemas/Corpus'
    patch:
      summary: Updates a single corpus by ID.
      operationId: mcserver.app.api.corpusAPI.patch
      responses:
        200:
          description: Corpus object
          content:
            application/json:
              schema:
                $ref: '../openapi_models.yaml#/components/schemas/Corpus'
      parameters:
        - name: author
          in: query
          description: Author of the texts in the corpus.
          required: false
          schema:
            type: string
            example: Aulus Gellius
        - name: source_urn
          in: query
          description: CTS base URN for referencing the corpus.
          required: false
          schema:
            type: string
            example: urn:cts:latinLit:phi1254.phi001.perseus-lat2
        - name: title
          in: query
          description: Corpus title.
          required: false
          schema:
            type: string
            example: Noctes Atticae
  /exercise:
    get:
      summary: Returns exercise data by ID.
      operationId: mcserver.app.api.exerciseAPI.get
      responses:
        200:
          description: Exercise data object, including a graph model for linguistic annotations.
          content:
            application/json:
              schema:
                $ref: '../openapi_models.yaml#/components/schemas/AnnisResponse'
      parameters:
        - name: eid
          in: query
          description: Unique identifier (UUID) for the exercise.
          required: true
          schema:
            type: string
            example: 12345678-1234-5678-1234-567812345678
    post:
      summary: Creates a new exercise.
      operationId: mcserver.app.api.exerciseAPI.post
      responses:
        200:
          description: Exercise data object
          content:
            application/json:
              schema:
                $ref: '../openapi_models.yaml#/components/schemas/AnnisResponse'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '../openapi_models.yaml#/components/schemas/ExerciseForm'
  /exerciseList:
    get:
      summary: Provides metadata for all available exercises.
      operationId: mcserver.app.api.exerciseListAPI.get
      responses:
        200:
          description: Data for interactive exercises, excluding the linguistic details.
          content:
            application/json:
              schema:
                $ref: '../openapi_models.yaml#/components/schemas/Exercise'
      parameters:
        - name: lang
          in: query
          description: ISO 639-1 Language Code for the localization of exercise content.
          required: true
          schema:
            type: string
            example: en
        - name: frequency_upper_bound
          in: query
          description: Upper bound for reference vocabulary frequency.
          required: false
          schema:
            type: integer
            example: 500
            default: 0
        - name: last_update_time
          in: query
          description: Time (in milliseconds) of the last update.
          required: false
          schema:
            type: integer
            example: 123456789
            default: 0
        - name: vocabulary
          in: query
          description: Identifier for a reference vocabulary.
          required: false
          schema:
            type: string
            enum: [agldt, bws, proiel, viva]
            example: agldt
  /file:
    get:
      summary: Provides the URL to download a specific file.
      operationId: mcserver.app.api.fileAPI.get
      responses:
        200:
          description: Data for interactive exercises, excluding the linguistic details.
          content:
            application/json:
              schema:
                $ref: '../openapi_models.yaml#/components/schemas/Exercise'
      parameters:
        - name: id
          in: query
          description: Unique identifier (UUID) for an exercise.
          required: true
          schema:
            type: string
            example: 12345678-1234-5678-1234-567812345678
        - name: type
          in: query
          description: File format for the requested download.
          required: true
          schema:
            $ref: '../openapi_models.yaml#/components/schemas/FileType'
        - name: solution_indices
          in: query
          description: Indices for the solutions that should be included in the download.
          required: false
          schema:
            type: array
            items:
              type: integer
              example: 0
            default: []
    post:
      summary: Serializes and persists learning results or HTML content for later access.
      operationId: mcserver.app.api.fileAPI.post
      responses:
        200:
          description: Indication of success, possibly a reference to the resulting file.
          content:
            application/json:
              schema:
                type: string
                description: Indication of success, or name of the file that was generated.
                example: 12345678-1234-5678-1234-567812345678.pdf
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              description: Data that should be serialized and persisted.
              x-body-name: file_data
              properties:
                file_type:
                  $ref: '../openapi_models.yaml#/components/schemas/FileType'
                html_content:
                  type: string
                  description: HTML content to be serialized.
                  example: <html></html>
                learning_result:
                  type: string
                  description: Serialized XAPI results for an interactive exercise.
                  example: "{'0': {}}"
                urn:
                  type: string
                  description: CTS URN for the text passage from which the HTML content was created.
                  example: urn:cts:latinLit:phi0448.phi001.perseus-lat2:1.1.1
  /frequency:
    get:
      summary: Returns results for a frequency query from ANNIS for a given CTS URN.
      operationId: mcserver.app.api.frequencyAPI.get
      responses:
        200:
          description: Frequency analysis, i.e. a list of frequency items.
          content:
            application/json:
              schema:
                type: array
                description: List of items with frequency data for linguistic phenomena.
                items:
                  $ref: "../openapi_models.yaml#/components/schemas/FrequencyItem"
      parameters:
        - name: urn
          in: query
          description: CTS URN for referencing the corpus.
          required: true
          schema:
            type: string
            example: urn:cts:latinLit:phi1254.phi001.perseus-lat2:5.6.21-5.6.21
  /staticExercises:
    get:
      summary: Returns metadata for static exercises.
      operationId: mcserver.app.api.staticExercisesAPI.get
      responses:
        200:
          description: Metadata for static exercises, mapped to their respective URIs in the frontend.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '../openapi_models.yaml#/components/schemas/StaticExercise'
