openapi: "3.0.0"

info:
  title: Machina Callida Backend REST API (Corpus Storage Manager)
  version: "1.0"
servers:
  - url: http://localhost:6555/mc/api/v1.0

paths:
  /frequency:
    get:
      summary: Returns results for a frequency query from ANNIS for a given CTS URN.
      operationId: csm.app.api.frequencyAPI.get
      responses:
        200:
          description: Frequency analysis, i.e. a list of frequency items.
          content:
            application/json:
              schema:
                type: array
                description: List of items with frequency data for linguistic phenomena.
                items:
                  $ref: "../openapi_models.yaml#/components/schemas/FrequencyItem"
      parameters:
        - $ref: '../openapi_models.yaml#/components/parameters/UrnParam'
  /textcomplexity:
    post:
      summary: Gives users measures of text complexity for a given text.
      operationId: csm.app.api.textcomplexityAPI.post
      responses:
        200:
          description: Text complexity measures for a given text.
          content:
            application/json:
              schema:
                $ref: '../openapi_models.yaml#/components/schemas/TextComplexity'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '../openapi_models.yaml#/components/schemas/TextComplexityFormBase'
