/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Paths to the data directories for various H5P exercise types.
 */
export type ExerciseTypePath = 'drag_text' | 'fill_blanks' | 'mark_words' | 'multi_choice' | 'voc_list';

export const ExerciseTypePath = {
    DragText: 'drag_text' as ExerciseTypePath,
    FillBlanks: 'fill_blanks' as ExerciseTypePath,
    MarkWords: 'mark_words' as ExerciseTypePath,
    MultiChoice: 'multi_choice' as ExerciseTypePath,
    VocList: 'voc_list' as ExerciseTypePath
};

