/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Additional exercise data.
 */
export interface ExerciseFormAllOf { 
    /**
     * Type of exercise, concerning interaction and layout.
     */
    type: string;
    /**
     * Localized expression of the exercise type.
     */
    type_translation?: string;
    /**
     * CTS URN for the text passage from which the exercise was created.
     */
    urn?: string;
}

