/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExerciseForm } from './exerciseForm';
import { ExerciseBase } from './exerciseBase';


export interface ExerciseFormComp { 
    /**
     * Feedback for successful completion of the exercise.
     */
    correct_feedback?: string;
    /**
     * Feedback for finishing the exercise.
     */
    general_feedback?: string;
    /**
     * Feedback for failing to complete the exercise successfully.
     */
    incorrect_feedback?: string;
    /**
     * Hints for how to complete the exercise.
     */
    instructions: string;
    /**
     * Feedback for successfully completing certain parts of the exercise.
     */
    partially_correct_feedback?: string;
    /**
     * Search queries that were used to build the exercise.
     */
    search_values: string;
    /**
     * Name of the person who wrote the base text for the exercise.
     */
    work_author?: string;
    /**
     * Title of the base text for the exercise.
     */
    work_title?: string;
    /**
     * Type of exercise, concerning interaction and layout.
     */
    type: string;
    /**
     * Localized expression of the exercise type.
     */
    type_translation?: string;
    /**
     * CTS URN for the text passage from which the exercise was created.
     */
    urn?: string;
}

