/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Additional data for creating and evaluating interactive exercises.
 */
export interface ExerciseExtension { 
    /**
     * CONLL-formatted linguistic annotations represented as a single string.
     */
    conll?: string;
    /**
     * Unique identifier (UUID) for the exercise.
     */
    eid: string;
    /**
     * Type of exercise, concerning interaction and layout.
     */
    exercise_type?: string;
    /**
     * When the exercise was last accessed (as POSIX timestamp).
     */
    last_access_time: number;
    /**
     * Correct solutions for the exercise.
     */
    solutions?: string;
    /**
     * Overall text complexity as measured by the software\'s internal language analysis.
     */
    text_complexity?: number;
    /**
     * CTS URN for the text passage from which the exercise was created.
     */
    urn?: string;
}

