/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * File format for the requested serialization.
 */
export type FileType = 'docx' | 'json' | 'pdf' | 'xml';

export const FileType = {
    Docx: 'docx' as FileType,
    Json: 'json' as FileType,
    Pdf: 'pdf' as FileType,
    Xml: 'xml' as FileType
};

