/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExerciseTypePath } from './exerciseTypePath';


/**
 * Metadata for the H5P exercise.
 */
export interface H5PForm { 
    /**
     * Unique identifier (UUID) for the exercise.
     */
    eid?: string;
    exercise_type_path?: ExerciseTypePath;
    /**
     * ISO 639-1 Language Code for the localization of exercise content.
     */
    lang?: string;
    /**
     * Indices for the solutions that should be included in the download.
     */
    solution_indices?: Array<number>;
}

