/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileType } from './fileType';


/**
 * Data that should be serialized and persisted.
 */
export interface InlineObject { 
    file_type?: FileType;
    /**
     * HTML content to be serialized.
     */
    html_content?: string;
    /**
     * Serialized XAPI results for an interactive exercise.
     */
    learning_result?: string;
    /**
     * CTS URN for the text passage from which the HTML content was created.
     */
    urn?: string;
}

