/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Learner data for completed exercises.
 */
export interface LearningResult { 
    /**
     * H5P user ID, usually unique per device.
     */
    actor_account_name?: string;
    /**
     * Describes the kind of object that was recognized as actor.
     */
    actor_object_type?: string;
    /**
     * Link to the exercise type specification.
     */
    category_id?: string;
    /**
     * Describes the kind of object that was recognized as exercise.
     */
    category_object_type?: string;
    /**
     * JSON string containing a list of possible choices, each with ID and description.
     */
    choices?: string;
    /**
     * Whether the exercise was fully processed or not.
     */
    completion: boolean;
    /**
     * JSON string containing a list of possible solutions to the exercise, given as patterns of answers.
     */
    correct_responses_pattern: string;
    /**
     * When the learner data was received (POSIX timestamp).
     */
    created_time: number;
    /**
     * How many seconds it took a learner to complete the exercise.
     */
    duration?: string;
    /**
     * JSON string containing a mapping of keys and values (usually the local content ID, i.e. a versioning mechanism).
     */
    extensions?: string;
    /**
     * Exercise type.
     */
    interaction_type?: string;
    /**
     * Exercise content, possibly including instructions.
     */
    object_definition_description: string;
    /**
     * Type of object definition that is presented to the user.
     */
    object_definition_type?: string;
    /**
     * Type of object that is presented to the user.
     */
    object_object_type?: string;
    /**
     * Answer provided by the user, possibly as a pattern.
     */
    response: string;
    /**
     * Maximum possible score to be achieved in this exercise.
     */
    score_max: number;
    /**
     * Minimum score to be achieved in this exercise.
     */
    score_min: number;
    /**
     * Score that was actually achieved by the user in this exercise.
     */
    score_raw: number;
    /**
     * Relative score (between 0 and 1) that was actually achieved by the user in this exercise.
     */
    score_scaled?: number;
    /**
     * Whether the exercise was successfully completed or not.
     */
    success: boolean;
    /**
     * Type of action that was performed by the user.
     */
    verb_display?: string;
    /**
     * Link to the type of action that was performed by the user.
     */
    verb_id?: string;
}

