/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Link { 
    /**
     * Component name as given by ANNIS.
     */
    annis_component_name?: string;
    /**
     * Component type as given by ANNIS.
     */
    annis_component_type?: string;
    /**
     * ID of the source node for the edge.
     */
    source?: string;
    /**
     * ID of the target node for the edge.
     */
    target?: string;
    /**
     * Dependency relation described by the edge.
     */
    udep_deprel?: string;
}

