/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Extra data for comparison with a reference vocabulary.
 */
export interface MatchingExerciseAllOf { 
    /**
     * Localized expression of the exercise type.
     */
    exercise_type_translation?: string;
    /**
     * Percentage of words in the exercise that match a reference vocabulary.
     */
    matching_degree?: number;
}

