/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sentence with metadata
 */
export interface Sentence { 
    /**
     * Unique identifier (in the corpus).
     */
    id?: number;
    /**
     * Percentage of words in the sentence that match a reference vocabulary.
     */
    matching_degree?: number;
}

