/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnnisResponse } from './annisResponse';


/**
 * Relevant parameters for measuring the text complexity of a text passage.
 */
export interface TextComplexityFormBase { 
    /**
     * Label of the desired measure for text complexity.
     */
    measure: string;
    /**
     * CTS URN for the text passage from which the text complexity should be calculated.
     */
    urn: string;
    annis_response?: AnnisResponse;
}

