/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Mapping of various elements of text complexity to their corresponding values.
 */
export interface TextComplexity { 
    /**
     * Overall text complexity of the given corpus.
     */
    all?: number;
    /**
     * Average length of a word in the given corpus.
     */
    avg_w_len?: number;
    /**
     * Average number of words per sentence.
     */
    avg_w_per_sent?: number;
    /**
     * Lexical density of the given corpus.
     */
    lex_den?: number;
    /**
     * Number of ablativi absoluti in the given corpus.
     */
    n_abl_abs?: number;
    /**
     * Number of clauses in the given corpus.
     */
    n_clause?: number;
    /**
     * Number of gerunds in the given corpus.
     */
    n_gerund?: number;
    /**
     * Number of infinitives in the given corpus.
     */
    n_inf?: number;
    /**
     * Number of participles in the given corpus.
     */
    n_part?: number;
    /**
     * Number of punctuation signs in the given corpus.
     */
    n_punct?: number;
    /**
     * Number of sentences in the given corpus.
     */
    n_sent?: number;
    /**
     * Number of subclauses in the given corpus.
     */
    n_subclause?: number;
    /**
     * Number of distinct word forms in the given corpus.
     */
    n_types?: number;
    /**
     * Number of words in the given corpus.
     */
    n_w?: number;
    /**
     * Number of distinct part of speech tags in the given corpus.
     */
    pos?: number;
}

