/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Timestamps for updates of various resources.
 */
export interface UpdateInfo { 
    /**
     * When the resource was created (as POSIX timestamp).
     */
    created_time: number;
    /**
     * When the resource was last modified (as POSIX timestamp).
     */
    last_modified_time: number;
    /**
     * Name of the resource for which update timestamps are indexed.
     */
    resource_type: UpdateInfo.ResourceTypeEnum;
}
export namespace UpdateInfo {
    export type ResourceTypeEnum = 'cts_data' | 'exercise_list' | 'file_api_clean';
    export const ResourceTypeEnum = {
        CtsData: 'cts_data' as ResourceTypeEnum,
        ExerciseList: 'exercise_list' as ResourceTypeEnum,
        FileApiClean: 'file_api_clean' as ResourceTypeEnum
    };
}


