/**
 * Machina Callida Backend REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VocabularyMC } from './vocabularyMC';


/**
 * Relevant parameters for comparing a corpus to a reference vocabulary.
 */
export interface VocabularyForm { 
    /**
     * Upper bound for reference vocabulary frequency.
     */
    frequency_upper_bound: number;
    /**
     * URN for the query corpus.
     */
    query_urn: string;
    vocabulary: VocabularyMC;
}

